go

CREATE SCHEMA CONDOMINIUM;

go

use p1g1;

CREATE TABLE CONDOMINIUM.PREDIO (
	ID int IDENTITY(1,1),
	Nome varchar(50) NOT NULL,
	Morada varchar(100),
	Cidade varchar(25),
	Codigo_Postal char(8),
	Latitude decimal(12,9) NOT NULL,
	Longitude decimal(12,9) NOT NULL,
	Area decimal(8,2),
	PRIMARY KEY(ID),
	CHECK(Area >= 0),
	CHECK(Latitude <= 90 AND Latitude >= -90),
	CHECK(Longitude <= 180 AND Longitude >= -180)
);

CREATE TABLE CONDOMINIUM.FOTOS_PREDIO (
	ID int,
	Localizacao_ficheiro varchar(100),
	PRIMARY KEY(ID, Localizacao_ficheiro),
	FOREIGN KEY (ID) REFERENCES PREDIO(ID)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CONDOMINIUM.ORCAMENTO (
	ID int IDENTITY(1,1),
	Titulo varchar(25) NOT NULL,
	Descricao varchar(100),
	Data_Inicial date NOT NULL,
	Data_Final date NOT NULL,
	ID_Predio int NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY (ID_Predio) REFERENCES CONDOMINIUM.PREDIO(ID)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CHECK (Data_Inicial<=Data_Final)
);

CREATE TABLE CONDOMINIUM.ITEM (
	nome varchar(50),
	orcamento_ID int,
	balanco DECIMAL(19,2) NOT NULL,
	PRIMARY KEY(nome, orcamento_ID),
	FOREIGN KEY(orcamento_ID) REFERENCES CONDOMINIUM.ORCAMENTO(ID)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CONDOMINIUM.FRACAO (
	ID int IDENTITY(1,1),
	Piso int NOT NULL,
	Zona varchar(15),
	Quota DECIMAL(19,2),
	Area DECIMAL(8,2) NOT NULL,
	Tipo Varchar(25) NOT NULL,
	ID_Predio int NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY (ID_Predio) REFERENCES CONDOMINIUM.PREDIO(ID)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CHECK (Area>=0),
	CHECK (Quota>=0)
);

CREATE TABLE CONDOMINIUM.FOTO_FRACAO (
	ID_Fracao int,
	Localizacao_ficheiro varchar(100),
	PRIMARY KEY(ID_Fracao, Localizacao_ficheiro),
	FOREIGN KEY(ID_Fracao) REFERENCES CONDOMINIUM.FRACAO(ID)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CONDOMINIUM.PAGAMENTO_QUOTA (
	ID int IDENTITY(1,1),
	Data date NOT NULL,
	Balanco DECIMAL(19,2) NOT NULL,
	ID_Fracao int NOT NULL,
	Mes DATE NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID_Fracao) REFERENCES CONDOMINIUM.FRACAO(ID)
	ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE CONDOMINIUM.SUJEITO_FISCAL (
	NIF char(9),
	Nome varchar(50) NOT NULL,
	e_mail varchar(50),
	Morada varchar(100),
	PRIMARY KEY(NIF)
);

CREATE TABLE CONDOMINIUM.OUTROS_PAGAMENTOS (
	ID int IDENTITY(1,1),
	Data date NOT NULL,
	Balanco DECIMAL(19,2) NOT NULL,
	Descricao varchar(100),
	suj_fiscal_nif char(9) NOT NULL,
	ID_Predio int NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY (ID_Predio) REFERENCES CONDOMINIUM.PREDIO(ID)
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (suj_fiscal_nif) REFERENCES CONDOMINIUM.SUJEITO_FISCAL(NIF)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CONDOMINIUM.CONDOMINO(
	CC char(8),
	Nome varchar(50) NOT NULL,
	NIF char(9) NOT NULL,
	e_mail varchar(50),
	PRIMARY KEY(CC),
	UNIQUE(NIF)
);

CREATE TABLE CONDOMINIUM.COMPRA (
	ID int IDENTITY(1,1),
	ID_Fracao int NOT NULL,
	CC_Condomino char(8) NOT NULL,
	Data_compra date NOT NULL,
	Data_venda date,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID_Fracao) REFERENCES CONDOMINIUM.FRACAO(ID)
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (CC_Condomino) REFERENCES CONDOMINIUM.CONDOMINO(CC)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CHECK(Data_venda>=Data_Compra OR DATA_venda IS NULL)
);


CREATE TABLE CONDOMINIUM.REUNIAO (
	ID int IDENTITY(1,1),
	ID_Predio int NOT NULL,
	Data date NOT NULL,
	Titulo varchar(25) NOT NULL,
	Descricao varchar(100),
	Ata varchar(1000),
	PRIMARY KEY(ID),
	FOREIGN KEY (ID_Predio) REFERENCES CONDOMINIUM.PREDIO(ID)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CONDOMINIUM.NOTA (
	ID int IDENTITY(1,1),
	ID_Predio int NOT NULL,
	Data date NOT NULL,
	Titulo varchar(25) NOT NULL,
	Descricao varchar(100),
	PRIMARY KEY(ID),
	FOREIGN KEY (ID_Predio) REFERENCES CONDOMINIUM.PREDIO(ID)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CONDOMINIUM.AVISO (
	ID int IDENTITY(1,1),
	ID_Predio int NOT NULL,
	Data date NOT NULL,
	Titulo varchar(25) NOT NULL,
	Descricao varchar(100),
	PRIMARY KEY(ID),
	FOREIGN KEY (ID_Predio) REFERENCES CONDOMINIUM.PREDIO(ID)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CONDOMINIUM.MANUTENCAO (
	ID int IDENTITY(1,1),
	ID_Predio int NOT NULL,
	Data date NOT NULL,
	Titulo varchar(25) NOT NULL,
	Descricao varchar(100),
	tipo varchar(25),
	Id_Outros_Pagamentos int,
	PRIMARY KEY(ID),
	FOREIGN KEY (Id_Outros_Pagamentos) REFERENCES CONDOMINIUM.OUTROS_PAGAMENTOS(ID)
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (ID_Predio) REFERENCES CONDOMINIUM.PREDIO(ID)
);

CREATE TABLE CONDOMINIUM.CONDOMINO_PARTICIPA_REUNIAO (
	ID_Reuniao int,
	CC char(8),
	PRIMARY KEY(ID_Reuniao, CC),
	FOREIGN KEY (ID_Reuniao) REFERENCES CONDOMINIUM.REUNIAO(ID)
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (CC) REFERENCES CONDOMINIUM.CONDOMINO(CC)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CONDOMINIUM.CONDOMINO_RECEBE_AVISO (
	ID_Aviso int,
	CC char(8),
	PRIMARY KEY(ID_Aviso,  CC),
	FOREIGN KEY (ID_Aviso) REFERENCES CONDOMINIUM.AVISO(ID)
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (CC) REFERENCES CONDOMINIUM.CONDOMINO(CC)
	ON DELETE CASCADE ON UPDATE CASCADE
);
